name: Feature request
description: Request a feature
labels: [ "enhancement" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: "Description of feature"
      description: "A clear and concise description of what the feature is."
    validations:
      required: true
