name: C/C++ CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
  
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build release 
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bspguy-windows
        path: build/Release

  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Download and install dependencies
      run: |
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglfw3-dev libglew-dev libxxf86vm-dev libfreetype6-dev

    - name: Build release
      run: |
        mkdir build; cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bspguy-linux
        path: build/bspguy
